### ISSUE TITLE
Always Too Many Iron Hands Primarchs

### ISSUE THREAD

**Issue by Squiggzz** [LeonisAstra/horus-heresy-panoptica#4]
JOE

HI JOE

So, whenever I make an Iron Hands list of any sort and add Ferrus into it, no matter what else is going on (points level, RoW, whatever), BScribe is telling me I have too many Primarchs (maximum 1). No idea what might be causing that issue.

Haven't tried adding Primarchs to any other Legion lists just yet. Iron Hands, tho, appear to have a ghost primarch in all their lists! Fitting?

**Comment by LeonisAstra** [comment]
If you are running Bitter Iron (which I believe you are), you cannot have Ferrus Manus in your list.

~ Joe G.

**Comment by LeonisAstra** [comment]
This is a bug from the BSData/horus-heresy upstream (https://github.com/BSData/horus-heresy/pull/3160). Because Primarch is used both as a slot and a unit type, it needed to be incremented by 1 to 2 maximum.

This is fixed now in commit 07132cd15b4236602a1e8f3b793ebc4b45b59ef4 .

~ Joe G.
